//priority:5000
//避免require导致的隔离脚本导致无法获取正常补全
//通一导入class应用，避免反复导入

let { $Color } = require("packages/java/awt/$Color")
let { $GLFW } = require("packages/org/lwjgl/glfw/$GLFW")
let { $MobEffect } = require("packages/net/minecraft/world/effect/$MobEffect")
let { $ContainerScreenEvent$Render$Foreground } = require("packages/net/minecraftforge/client/event/$ContainerScreenEvent$Render$Foreground")
let { $Button } = require("packages/net/minecraft/client/gui/components/$Button")
let { $ImageButton } = require("packages/net/minecraft/client/gui/components/$ImageButton")
let { $Tooltip } = require("packages/net/minecraft/client/gui/components/$Tooltip")
let { $InventoryScreen } = require("packages/net/minecraft/client/gui/screens/inventory/$InventoryScreen")
let { $LecternScreen } = require("packages/net/minecraft/client/gui/screens/inventory/$LecternScreen")
let { $ScreenEvent$Init$Post } = require("packages/net/minecraftforge/client/event/$ScreenEvent$Init$Post")
let { $ScreenEvent$Render$Post } = require("packages/net/minecraftforge/client/event/$ScreenEvent$Render$Post")
let { $ScreenEvent$Render$Pre } = require("packages/net/minecraftforge/client/event/$ScreenEvent$Render$Pre")
let { $GuiGraphics } = require("packages/net/minecraft/client/gui/$GuiGraphics")
let { $RenderNameTagEvent } = require("packages/net/minecraftforge/client/event/$RenderNameTagEvent")
let { $LivingEntity } = require("packages/net/minecraft/world/entity/$LivingEntity")
let { $RenderGuiEvent$Post } = require("packages/net/minecraftforge/client/event/$RenderGuiEvent$Post")
let { $KubeJS } = require("packages/dev/latvian/mods/kubejs/$KubeJS")
let { $RenderLivingEvent } = require("packages/net/minecraftforge/client/event/$RenderLivingEvent")
let { $AttackEntityEvent } = require("packages/net/minecraftforge/event/entity/player/$AttackEntityEvent")
let { $GameProfile } = require("packages/com/mojang/authlib/$GameProfile")
let { $PlayerFaceRenderer } = require("packages/net/minecraft/client/gui/components/$PlayerFaceRenderer")
let { $RenderLivingEvent$Post } = require("packages/net/minecraftforge/client/event/$RenderLivingEvent$Post")
let { $RenderTooltipEvent } = require("packages/net/minecraftforge/client/event/$RenderTooltipEvent")
let { $RenderTooltipEvent$GatherComponents } = require("packages/net/minecraftforge/client/event/$RenderTooltipEvent$GatherComponents")
let { $RenderTooltipEvent$Pre } = require("packages/net/minecraftforge/client/event/$RenderTooltipEvent$Pre")
let { $ScreenEvent$MouseButtonPressed$Post } = require("packages/net/minecraftforge/client/event/$ScreenEvent$MouseButtonPressed$Post")
let { $ScreenEvent$MouseDragged$Post } = require("packages/net/minecraftforge/client/event/$ScreenEvent$MouseDragged$Post")
let { $ScreenEvent$MouseScrolled$Post } = require("packages/net/minecraftforge/client/event/$ScreenEvent$MouseScrolled$Post")
let { $ScreenEvent$Opening } = require("packages/net/minecraftforge/client/event/$ScreenEvent$Opening")
let { $CustomizeGuiOverlayEvent$BossEventProgress } = require("packages/net/minecraftforge/client/event/$CustomizeGuiOverlayEvent$BossEventProgress")
let { $RenderLevelStageEvent } = require("packages/net/minecraftforge/client/event/$RenderLevelStageEvent")
let { $RenderLevelStageEvent$Stage } = require("packages/net/minecraftforge/client/event/$RenderLevelStageEvent$Stage")
let { $LivingAttackEvent } = require("packages/net/minecraftforge/event/entity/living/$LivingAttackEvent")
let { $LivingDamageEvent } = require("packages/net/minecraftforge/event/entity/living/$LivingDamageEvent")
let { $LivingHealEvent } = require("packages/net/minecraftforge/event/entity/living/$LivingHealEvent")
let { $LivingHurtEvent } = require("packages/net/minecraftforge/event/entity/living/$LivingHurtEvent")
let { $ScreenEvent$CharacterTyped$Post } = require("packages/net/minecraftforge/client/event/$ScreenEvent$CharacterTyped$Post")
let { $ScreenEvent$KeyPressed$Post } = require("packages/net/minecraftforge/client/event/$ScreenEvent$KeyPressed$Post")
let { $Either } = require("packages/com/mojang/datafixers/util/$Either")
let { $NonNullList } = require("packages/net/minecraft/core/$NonNullList")
let { $BundleTooltip } = require("packages/net/minecraft/world/inventory/tooltip/$BundleTooltip")
let { $RenderGuiEvent$Pre } = require("packages/net/minecraftforge/client/event/$RenderGuiEvent$Pre")
let { $RenderTooltipEvent$Color } = require("packages/net/minecraftforge/client/event/$RenderTooltipEvent$Color")

myRequire.$GLFW = $GLFW
myRequire.$Color = $Color
myRequire.$MobEffect = $MobEffect
myRequire.$ContainerScreenEvent$Render$Foreground = $ContainerScreenEvent$Render$Foreground
myRequire.$Button = $Button
myRequire.$ImageButton = $ImageButton
myRequire.$Tooltip = $Tooltip
myRequire.$InventoryScreen = $InventoryScreen
myRequire.$ScreenEvent$Init$Post = $ScreenEvent$Init$Post
myRequire.$LecternScreen = $LecternScreen
myRequire.$ScreenEvent$Render$Post = $ScreenEvent$Render$Post
myRequire.$ScreenEvent$Render$Pre = $ScreenEvent$Render$Pre
myRequire.$GuiGraphics = $GuiGraphics
myRequire.$RenderNameTagEvent = $RenderNameTagEvent
myRequire.$LivingEntity = $LivingEntity
myRequire.$RenderGuiEvent$Post = $RenderGuiEvent$Post
myRequire.$KubeJS = $KubeJS
myRequire.$RenderLivingEvent = $RenderLivingEvent
myRequire.$AttackEntityEvent = $AttackEntityEvent
myRequire.$RenderLivingEvent$Post = $RenderLivingEvent$Post
myRequire.$RenderTooltipEvent = $RenderTooltipEvent
myRequire.$RenderTooltipEvent$GatherComponents = $RenderTooltipEvent$GatherComponents
myRequire.$RenderTooltipEvent$Pre = $RenderTooltipEvent$Pre
myRequire.$GameProfile = $GameProfile
myRequire.$PlayerFaceRenderer = $PlayerFaceRenderer
myRequire.$ScreenEvent$MouseButtonPressed$Post = $ScreenEvent$MouseButtonPressed$Post
myRequire.$ScreenEvent$MouseDragged$Post = $ScreenEvent$MouseDragged$Post
myRequire.$ScreenEvent$MouseScrolled$Post = $ScreenEvent$MouseScrolled$Post
myRequire.$ScreenEvent$Opening = $ScreenEvent$Opening
myRequire.$CustomizeGuiOverlayEvent$BossEventProgress =$CustomizeGuiOverlayEvent$BossEventProgress
myRequire.$RenderLevelStageEvent =$RenderLevelStageEvent
myRequire.$RenderLevelStageEvent$Stage =$RenderLevelStageEvent$Stage
myRequire.$LivingAttackEvent =$LivingAttackEvent
myRequire.$LivingDamageEvent =$LivingDamageEvent
myRequire.$LivingHealEvent =$LivingHealEvent
myRequire.$LivingHurtEvent =$LivingHurtEvent
myRequire.$ScreenEvent$CharacterTyped$Post =$ScreenEvent$CharacterTyped$Post
myRequire.$ScreenEvent$KeyPressed$Post =$ScreenEvent$KeyPressed$Post
myRequire.$Either =$Either
myRequire.$NonNullList =$NonNullList
myRequire.$BundleTooltip=$BundleTooltip
myRequire.$RenderGuiEvent$Pre=$RenderGuiEvent$Pre
myRequire.$RenderTooltipEvent$Color=$RenderTooltipEvent$Color