#This file stores configuration options for Iris, such as the currently active shaderpack
#Thu Apr 03 20:55:24 CST 2025
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
maxShadowRenderDistance=32
shaderPack=ComplementaryReimagined_r5.4 + EuphoriaPatches_1.5.2
enableShaders=true
